version: '3.4'

services:
  tasktracker:
    image: ${DOCKER_REGISTRY-}tasktrackerweb
    build:
      context: .
      dockerfile: src/TaskTracker.Web/Dockerfile
    depends_on:
      - "sqlserver"
  tasktracker.publicapi:
    image: ${DOCKER_REGISTRY-}tasktrackerpublicapi
    build:
      context: .
      dockerfile: src/TaskTracker.PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y